#!/bin/bash
# http://thales.cica.es/rd/glinex/practicas-glinex05/manuales/bash/practica.pdf
echo "-------------------------"
echo "Algunas variables de entorno"
echo "-------------------------"
echo "HOME: $HOME"
echo "PATH: $PATH"
echo "LOGNAME: $LOGNAME"
echo "SHELL: $SHELL"
echo "TERM: $TERM"
echo "-------------------------"
echo ""
echo "-------------------------"
echo "Algunas variables de locales"
echo "-------------------------"
echo "PPID: $PPID"
echo "PWD: $PWD"
echo "OLDPWD: $OLDPWD"
echo "RANDOM: $RANDOM"
echo "-------------------------"